#!/bin/sh

set -o nounset

show_help () {
cat <<EOF
usage: a2 start
   or: a2 stop
   or: a2 restart
   or: a2 status
EOF
}

cmd_status () {
    if is_running
    then
        printf "aria2c is running.\n"
    else
        printf "aria2c is stopped.\n"
    fi
}

cmd_stop () {
    is_running || return
    killall aria2c
}

cmd_restart () {
    cmd_stop
    sleep 1
    cmd_start
}

main () {
    local version="0.1.0"
    local logfile="$HOME/log"
    for arg in "$@"
    do
        case $arg in
        start)
            cmd_start "$@"
            exit
            ;;
        stop)
            cmd_stop "$@"
            exit
            ;;
        restart)
            cmd_restart "$@"
            exit
            ;;
        status)
            cmd_status "$@"
            exit
            ;;
        -V|--version)
            printf "%s\n" "$version"
            exit 0
            ;;
        --help)
            show_help
            exit 0
            ;;
        *)
            >&2 printf "error: invalid argument \`%s'\n" "$arg"
            exit 1
            ;;
        esac
    done
    show_help
}

cmd_start () {
    is_running && return 1
    test -e $HOME/.aria2/aria2.session || touch $HOME/.aria2/aria2.session
    nohup aria2c --conf-path=$HOME/.aria2/aria2.conf >>"$logfile" 2>&1 &
    is_running || tail $HOME/.aria2/aria2.log
}

is_running () {
    test -n "$(ps -ef | grep aria2c | grep -v grep)"
}

main "$@"
